/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodtestscheduler;

import javax.swing.JOptionPane;

/**
 *
 * @author gregm
 */
public class Display extends javax.swing.JFrame {//my jframe containing my GUI for 

    private StackADT<Patient> noShowerStack;//stack t0 store the appointments/patiens in a stack
    private PriorityQueueADT pq;//pq in order to store them based on priority
    private QueueADT fcfsQ;  //q in order to store appointmnet/patients in fcfs functionality
    private Appointment appointment;//an appoinment obj to acces manage and ahndle all patients/appointments, to acess appoinrment lgoic

    /**
     * Creates new form Display
     */
    public Display() {
        initComponents(); 

        pq = new PriorityQueueADT(); //make a new pq for handling basede on priority
        fcfsQ = new QueueADT(); 

        this.appointment = new Appointment(pq, fcfsQ);//init the appointment obj

        noShowerStack = new StackADT<>();  //init the stack so the no show tracker stack will function
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPNL = new javax.swing.JPanel();
        NavigationTabbedPane = new javax.swing.JTabbedPane();
        HomePNL = new javax.swing.JPanel();
        LogoLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ExitBTN = new javax.swing.JLabel();
        ManageAppointmentsPNL = new javax.swing.JPanel();
        HomeLBL = new javax.swing.JLabel();
        FirstNameLBL = new javax.swing.JLabel();
        SurnameLBL = new javax.swing.JLabel();
        AgeLBL = new javax.swing.JLabel();
        FirstNameFIeld = new javax.swing.JTextField();
        SurnameField = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        TestTypeComboBox = new javax.swing.JComboBox<>();
        TestTypeLBL = new javax.swing.JLabel();
        PriorityComboBox = new javax.swing.JComboBox<>();
        PriorityLBL = new javax.swing.JLabel();
        EmailLBL = new javax.swing.JLabel();
        AppointmentNumberFormattedField = new javax.swing.JFormattedTextField();
        AppointmentNumberLBL = new javax.swing.JLabel();
        RemoveBTN = new javax.swing.JButton();
        AddBTN = new javax.swing.JButton();
        EmailField = new javax.swing.JTextField();
        HospitalCheckBox = new javax.swing.JCheckBox();
        GPEmailLBL = new javax.swing.JLabel();
        GPEmailField = new javax.swing.JTextField();
        GPNotesLBL = new javax.swing.JLabel();
        GPNotesField = new javax.swing.JTextField();
        StatusLBL = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox<>();
        ViiewAppointmentsPriorityBTN = new javax.swing.JButton();
        UpcomingBTN1 = new javax.swing.JButton();
        ViewAppointmentsFCFSBtn = new javax.swing.JButton();
        ExitBTN1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1500, 750));

        BackgroundPNL.setBackground(new java.awt.Color(0, 0, 153));
        BackgroundPNL.setMaximumSize(new java.awt.Dimension(1500, 750));

        NavigationTabbedPane.setBackground(new java.awt.Color(0, 153, 255));
        NavigationTabbedPane.setForeground(new java.awt.Color(255, 255, 255));
        NavigationTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        NavigationTabbedPane.setAlignmentX(0.8F);
        NavigationTabbedPane.setAlignmentY(0.8F);
        NavigationTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NavigationTabbedPane.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NavigationTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavigationTabbedPaneMouseClicked(evt);
            }
        });

        HomePNL.setBackground(new java.awt.Color(0, 153, 255));

        LogoLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodtestscheduler/img/blood-test.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Blood Test Scheduler");

        ExitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodtestscheduler/img/button.png"))); // NOI18N
        ExitBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HomePNLLayout = new javax.swing.GroupLayout(HomePNL);
        HomePNL.setLayout(HomePNLLayout);
        HomePNLLayout.setHorizontalGroup(
            HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePNLLayout.createSequentialGroup()
                .addGap(442, 442, 442)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
            .addGroup(HomePNLLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(LogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HomePNLLayout.setVerticalGroup(
            HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePNLLayout.createSequentialGroup()
                .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePNLLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        NavigationTabbedPane.addTab("Home", HomePNL);

        ManageAppointmentsPNL.setBackground(new java.awt.Color(0, 153, 255));
        ManageAppointmentsPNL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ManageAppointmentsPNL.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        HomeLBL.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        HomeLBL.setForeground(new java.awt.Color(255, 255, 255));
        HomeLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLBL.setText("Manage Appointments");

        FirstNameLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FirstNameLBL.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameLBL.setText("First Name");

        SurnameLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        SurnameLBL.setForeground(new java.awt.Color(255, 255, 255));
        SurnameLBL.setText("Surname");

        AgeLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AgeLBL.setForeground(new java.awt.Color(255, 255, 255));
        AgeLBL.setText("Age");

        FirstNameFIeld.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        SurnameField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        AgeField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        TestTypeComboBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TestTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Complete Blood Count (CBC)", "Lipid Profile", "Liver Function Test", "Thyroid Function Test" }));

        TestTypeLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TestTypeLBL.setForeground(new java.awt.Color(255, 255, 255));
        TestTypeLBL.setText("Blood Test Type");

        PriorityComboBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PriorityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgent", "Medium", "Low" }));

        PriorityLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PriorityLBL.setForeground(new java.awt.Color(255, 255, 255));
        PriorityLBL.setText("Priority");

        EmailLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        EmailLBL.setForeground(new java.awt.Color(255, 255, 255));
        EmailLBL.setText("Email Adress");

        AppointmentNumberLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AppointmentNumberLBL.setForeground(new java.awt.Color(255, 255, 255));
        AppointmentNumberLBL.setText("Appointment no.");

        RemoveBTN.setText("Remove");
        RemoveBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RemoveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBTNActionPerformed(evt);
            }
        });

        AddBTN.setText("Add");
        AddBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });

        EmailField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        HospitalCheckBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        HospitalCheckBox.setText("Coming from a hospital ward?");
        HospitalCheckBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        GPEmailLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GPEmailLBL.setForeground(new java.awt.Color(255, 255, 255));
        GPEmailLBL.setText("GP Email");

        GPEmailField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        GPNotesLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GPNotesLBL.setForeground(new java.awt.Color(255, 255, 255));
        GPNotesLBL.setText("GP Notes");

        GPNotesField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        StatusLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        StatusLBL.setForeground(new java.awt.Color(255, 255, 255));
        StatusLBL.setText("Status");

        StatusComboBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Upcoming", "Completed", "No Show", " " }));

        ViiewAppointmentsPriorityBTN.setText("View appointments (Priority)");
        ViiewAppointmentsPriorityBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViiewAppointmentsPriorityBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViiewAppointmentsPriorityBTNActionPerformed(evt);
            }
        });

        UpcomingBTN1.setText("Display No-Shows");
        UpcomingBTN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpcomingBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpcomingBTN1ActionPerformed(evt);
            }
        });

        ViewAppointmentsFCFSBtn.setText("View appointments (Queue)");
        ViewAppointmentsFCFSBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewAppointmentsFCFSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAppointmentsFCFSBtnActionPerformed(evt);
            }
        });

        ExitBTN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodtestscheduler/img/button.png"))); // NOI18N
        ExitBTN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBTN1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ManageAppointmentsPNLLayout = new javax.swing.GroupLayout(ManageAppointmentsPNL);
        ManageAppointmentsPNL.setLayout(ManageAppointmentsPNLLayout);
        ManageAppointmentsPNLLayout.setHorizontalGroup(
            ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                                .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GPNotesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GPEmailLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TestTypeLBL))
                                .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(FirstNameFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TestTypeComboBox, 0, 203, Short.MAX_VALUE)
                                            .addComponent(GPEmailField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(GPNotesField)))))
                            .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                                .addComponent(AppointmentNumberLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AppointmentNumberFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailLBL)
                            .addComponent(AgeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SurnameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriorityLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StatusLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriorityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(HomeLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitBTN1))
                    .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                        .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(HospitalCheckBox))
                            .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(ViiewAppointmentsPriorityBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UpcomingBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ViewAppointmentsFCFSBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ManageAppointmentsPNLLayout.setVerticalGroup(
            ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(HomeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ExitBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AppointmentNumberFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AppointmentNumberLBL))
                        .addGap(19, 19, 19)
                        .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameLBL))
                        .addGap(16, 16, 16)
                        .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgeLBL)
                            .addComponent(TestTypeLBL)
                            .addComponent(TestTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ManageAppointmentsPNLLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailLBL))
                        .addGap(18, 18, 18)
                        .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SurnameLBL))
                        .addGap(17, 17, 17)
                        .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PriorityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriorityLBL)
                            .addComponent(GPEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GPEmailLBL))
                        .addGap(18, 18, 18)
                        .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatusLBL)
                            .addComponent(GPNotesField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GPNotesLBL)
                            .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)))
                .addComponent(HospitalCheckBox)
                .addGap(48, 48, 48)
                .addGroup(ManageAppointmentsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViiewAppointmentsPriorityBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpcomingBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewAppointmentsFCFSBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        NavigationTabbedPane.addTab("Manage Appointments", ManageAppointmentsPNL);

        javax.swing.GroupLayout BackgroundPNLLayout = new javax.swing.GroupLayout(BackgroundPNL);
        BackgroundPNL.setLayout(BackgroundPNLLayout);
        BackgroundPNLLayout.setHorizontalGroup(
            BackgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPNLLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(NavigationTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        BackgroundPNLLayout.setVerticalGroup(
            BackgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPNLLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(NavigationTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NavigationTabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavigationTabbedPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NavigationTabbedPaneMouseClicked

    private void ViiewAppointmentsPriorityBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViiewAppointmentsPriorityBTNActionPerformed
     String Cont = pq.printPQueue();//xall upon the displayQueue dunction
    JOptionPane.showMessageDialog(this, Cont, "Priority Scheduled Appointments * FROM BOTTOM TO TOP - PRIORITY *", JOptionPane.INFORMATION_MESSAGE);//peint out the patients appointments into a joption pane
    }//GEN-LAST:event_ViiewAppointmentsPriorityBTNActionPerformed

    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
        int appointmentNumber = Integer.parseInt(AppointmentNumberFormattedField.getText());//get the text the end user has entered into the fields
        String fName = FirstNameFIeld.getText();//get the text the end user has entered into the fields
        String surname = SurnameField.getText();//get the text the end user has entered into the fields
        String emailAddress = EmailField.getText();//get the text the end user has entered into the fields
        String bloodTestType = (String) TestTypeComboBox.getSelectedItem();//get the text the end user has entered into the fields
        String selectedPriority = (String) PriorityComboBox.getSelectedItem();//get the text the end user has entered into the fields
        int priorityNum;//get the text the end user has entered into the fields

        if ("Urgent".equals(selectedPriority)) {//if statement to convert the string choice to integers so we cna add it based on priority
            priorityNum = 1;//set to highest
        } else if ("Medium".equals(selectedPriority)) {//if mediu, is chosen
            priorityNum = 2;//set to medium
        } else if ("Low".equals(selectedPriority)) {//if low is chosen
            priorityNum = 3;//set to 3
        } else {//if none of the above happen
            priorityNum = 4;//set to 4
        }//end else

        String gpEmailAddress = GPEmailField.getText();//get the text the end user has entered into the fields
        String gpNotes = GPNotesField.getText();//get the text the end user has entered into the fields
        String appointmentStatus = (String) StatusComboBox.getSelectedItem();//get the text the end user has entered into the fields
        int age = Integer.parseInt(AgeField.getText());//get the text the end user has entered into the fields

        if (age > 50) {//add in additonal logic if age exceeds 50 move them to the highest peiority in the queue
            priorityNum = 1;//which is setting the priority num to 1
        }//end if

        if (HospitalCheckBox.isSelected()) {//if the "im coming from a hospital eard checkbox is ticked
            priorityNum = 1;//set to highest priority immeditaley regardless oif they put low priority
        }
        Patient patient = new Patient(appointmentNumber, fName, surname, emailAddress,bloodTestType, priorityNum, gpEmailAddress,gpNotes, appointmentStatus, age);//use all the data gathered from the fields inputted by the end iser and save it to a patient obj

        appointment.saveAppointment(priorityNum, patient);//now send the patient and the priority num to the save appointment method and thats were itll be added to both queues

        if ("No Show".equals(patient.getAppointmentStatus())) {//logic in order to add to no show stack
            noShowerStack.push(patient);//push them to the no shower stack thats used to track patients who dont show up
            System.out.println("a no shower has been added to the stack");//
        }

        JOptionPane.showMessageDialog(this, "Appointment saved succeful !!");//joptionpane to notify the end user
    }//GEN-LAST:event_AddBTNActionPerformed

    private void RemoveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBTNActionPerformed
if (pq.isEmpty() || fcfsQ.isEmpty()) {//if the pq is empty and the q good measure to check both 
    JOptionPane.showMessageDialog(null, "Queue empty. No appoinment to remove.", "Empty", JOptionPane.INFORMATION_MESSAGE);
} else {//else
    appointment.deleteAppointment();//call upon the delete appointment method in the appointment class
    System.out.println("Appointment deleted.");
}

        
    }//GEN-LAST:event_RemoveBTNActionPerformed

    private void UpcomingBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpcomingBTN1ActionPerformed
        String cont = noShowerStack.displayStack();//c\ll upon the displayQueue dunction
        JOptionPane.showMessageDialog(this, cont, "No-Showers", JOptionPane.INFORMATION_MESSAGE);//peint out the patients appointments into a joption pane
    }//GEN-LAST:event_UpcomingBTN1ActionPerformed

    private void ViewAppointmentsFCFSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAppointmentsFCFSBtnActionPerformed
    String cont = fcfsQ.displayQueue();//c\ll upon the displayQueue dunction
    JOptionPane.showMessageDialog(this, cont, "FCFS Scheduled *From top to bottom*", JOptionPane.INFORMATION_MESSAGE);//peint out the patients appointments into a joption pane
    }//GEN-LAST:event_ViewAppointmentsFCFSBtnActionPerformed

    private void ExitBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseClicked
System.exit(0); 
    }//GEN-LAST:event_ExitBTNMouseClicked

    private void ExitBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTN1MouseClicked
System.exit(0); 
    }//GEN-LAST:event_ExitBTN1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.JTextField AgeField;
    private javax.swing.JLabel AgeLBL;
    private javax.swing.JFormattedTextField AppointmentNumberFormattedField;
    private javax.swing.JLabel AppointmentNumberLBL;
    private javax.swing.JPanel BackgroundPNL;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLBL;
    private javax.swing.JLabel ExitBTN;
    private javax.swing.JLabel ExitBTN1;
    private javax.swing.JTextField FirstNameFIeld;
    private javax.swing.JLabel FirstNameLBL;
    private javax.swing.JTextField GPEmailField;
    private javax.swing.JLabel GPEmailLBL;
    private javax.swing.JTextField GPNotesField;
    private javax.swing.JLabel GPNotesLBL;
    private javax.swing.JLabel HomeLBL;
    private javax.swing.JPanel HomePNL;
    private javax.swing.JCheckBox HospitalCheckBox;
    private javax.swing.JLabel LogoLBL;
    private javax.swing.JPanel ManageAppointmentsPNL;
    private javax.swing.JTabbedPane NavigationTabbedPane;
    private javax.swing.JComboBox<String> PriorityComboBox;
    private javax.swing.JLabel PriorityLBL;
    private javax.swing.JButton RemoveBTN;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JLabel StatusLBL;
    private javax.swing.JTextField SurnameField;
    private javax.swing.JLabel SurnameLBL;
    private javax.swing.JComboBox<String> TestTypeComboBox;
    private javax.swing.JLabel TestTypeLBL;
    private javax.swing.JButton UpcomingBTN1;
    private javax.swing.JButton ViewAppointmentsFCFSBtn;
    private javax.swing.JButton ViiewAppointmentsPriorityBTN;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
