/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodtestscheduler;

/**
 *
 * @author gregm
 */
public class Display extends javax.swing.JFrame {

    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPNL = new javax.swing.JPanel();
        NavigationTabbedPane = new javax.swing.JTabbedPane();
        HomePNL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FirstNameLBL = new javax.swing.JLabel();
        SurnameLBL = new javax.swing.JLabel();
        AgeLBL = new javax.swing.JLabel();
        FirstNameFIeld = new javax.swing.JTextField();
        SurnameField = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        TestTypeComboBox = new javax.swing.JComboBox<>();
        TestTypeLBL = new javax.swing.JLabel();
        PriorityComboBox = new javax.swing.JComboBox<>();
        PriorityLBL = new javax.swing.JLabel();
        EmailLBL = new javax.swing.JLabel();
        AppointmentNumberFormattedField = new javax.swing.JFormattedTextField();
        AppointmentNumberLBL = new javax.swing.JLabel();
        DeleteBTN = new javax.swing.JButton();
        SaveBTN = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();
        EmailField = new javax.swing.JTextField();
        UpdateBTN1 = new javax.swing.JButton();
        HospitalCheck = new javax.swing.JCheckBox();
        GPEmailLBL = new javax.swing.JLabel();
        GPEmailField = new javax.swing.JTextField();
        GPNotesLBL = new javax.swing.JLabel();
        GPEmailField1 = new javax.swing.JTextField();
        GPNotesLBL1 = new javax.swing.JLabel();
        GPEmailField2 = new javax.swing.JTextField();
        AppointmentQueue = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AppointmentQueueTBL = new javax.swing.JTable();
        PopulateTableBTN = new javax.swing.JButton();
        AppointmentQueueLBL = new javax.swing.JLabel();
        NoShowPNL = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1500, 750));

        BackgroundPNL.setBackground(new java.awt.Color(0, 0, 153));
        BackgroundPNL.setMaximumSize(new java.awt.Dimension(1500, 750));

        NavigationTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        HomePNL.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home");

        FirstNameLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FirstNameLBL.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameLBL.setText("First Name");

        SurnameLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        SurnameLBL.setForeground(new java.awt.Color(255, 255, 255));
        SurnameLBL.setText("Surname");

        AgeLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AgeLBL.setForeground(new java.awt.Color(255, 255, 255));
        AgeLBL.setText("Age");

        FirstNameFIeld.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        SurnameField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        AgeField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        TestTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TestTypeLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TestTypeLBL.setForeground(new java.awt.Color(255, 255, 255));
        TestTypeLBL.setText("Test Type");

        PriorityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgent", "Medium", "Low", " " }));

        PriorityLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PriorityLBL.setForeground(new java.awt.Color(255, 255, 255));
        PriorityLBL.setText("Priority");

        EmailLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        EmailLBL.setForeground(new java.awt.Color(255, 255, 255));
        EmailLBL.setText("Email Adress");

        AppointmentNumberLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AppointmentNumberLBL.setForeground(new java.awt.Color(255, 255, 255));
        AppointmentNumberLBL.setText("Appointment number");

        DeleteBTN.setText("Delete");

        SaveBTN.setText("Save");

        UpdateBTN.setText("Update");

        EmailField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        UpdateBTN1.setText("Read");

        HospitalCheck.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        HospitalCheck.setForeground(new java.awt.Color(255, 255, 255));
        HospitalCheck.setText("Coming from the hospital?");

        GPEmailLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GPEmailLBL.setForeground(new java.awt.Color(255, 255, 255));
        GPEmailLBL.setText("GP Email");

        GPEmailField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        GPNotesLBL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GPNotesLBL.setForeground(new java.awt.Color(255, 255, 255));
        GPNotesLBL.setText("GP Notes");

        GPEmailField1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        GPNotesLBL1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GPNotesLBL1.setForeground(new java.awt.Color(255, 255, 255));
        GPNotesLBL1.setText("GP Clinic name");

        GPEmailField2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GPEmailField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPEmailField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomePNLLayout = new javax.swing.GroupLayout(HomePNL);
        HomePNL.setLayout(HomePNLLayout);
        HomePNLLayout.setHorizontalGroup(
            HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePNLLayout.createSequentialGroup()
                .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePNLLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePNLLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TestTypeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GPNotesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GPEmailLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HomePNLLayout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TestTypeComboBox, 0, 203, Short.MAX_VALUE)
                                            .addComponent(GPEmailField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(GPEmailField1)))
                                    .addGroup(HomePNLLayout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(FirstNameFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(HomePNLLayout.createSequentialGroup()
                                .addComponent(AppointmentNumberLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AppointmentNumberFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(220, 220, 220)
                        .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailLBL)
                            .addComponent(AgeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SurnameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriorityLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GPNotesLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PriorityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GPEmailField2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(HomePNLLayout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomePNLLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HospitalCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HomePNLLayout.createSequentialGroup()
                                .addComponent(SaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(UpdateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(UpdateBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        HomePNLLayout.setVerticalGroup(
            HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePNLLayout.createSequentialGroup()
                .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AppointmentNumberFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AppointmentNumberLBL))
                        .addGap(19, 19, 19)
                        .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameLBL))
                        .addGap(16, 16, 16)
                        .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgeLBL)
                            .addComponent(TestTypeLBL)
                            .addComponent(TestTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(HomePNLLayout.createSequentialGroup()
                        .addGap(20, 134, Short.MAX_VALUE)
                        .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailLBL))
                        .addGap(18, 18, 18)
                        .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SurnameLBL))
                        .addGap(17, 17, 17)
                        .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PriorityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriorityLBL)
                            .addComponent(GPEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GPEmailLBL))
                        .addGap(18, 18, 18)
                        .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GPEmailField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GPNotesLBL1)
                            .addComponent(GPEmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GPNotesLBL))
                        .addGap(69, 69, 69)))
                .addComponent(HospitalCheck)
                .addGap(34, 34, 34)
                .addGroup(HomePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        NavigationTabbedPane.addTab("Home", HomePNL);

        AppointmentQueue.setBackground(new java.awt.Color(0, 153, 255));

        AppointmentQueueTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "AppointmentNumber", "First Name", "Surname", "Email", "Test Type", "Age", "Priority", "GP Email", "GP Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AppointmentQueueTBL);
        if (AppointmentQueueTBL.getColumnModel().getColumnCount() > 0) {
            AppointmentQueueTBL.getColumnModel().getColumn(8).setHeaderValue("GP Notes");
        }

        PopulateTableBTN.setText("Populate Table");

        AppointmentQueueLBL.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        AppointmentQueueLBL.setForeground(new java.awt.Color(255, 255, 255));
        AppointmentQueueLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppointmentQueueLBL.setText("Appointment queue");

        javax.swing.GroupLayout AppointmentQueueLayout = new javax.swing.GroupLayout(AppointmentQueue);
        AppointmentQueue.setLayout(AppointmentQueueLayout);
        AppointmentQueueLayout.setHorizontalGroup(
            AppointmentQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentQueueLayout.createSequentialGroup()
                .addGroup(AppointmentQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppointmentQueueLayout.createSequentialGroup()
                        .addGap(526, 526, 526)
                        .addComponent(PopulateTableBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AppointmentQueueLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1084, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AppointmentQueueLayout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addComponent(AppointmentQueueLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        AppointmentQueueLayout.setVerticalGroup(
            AppointmentQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentQueueLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(AppointmentQueueLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PopulateTableBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        NavigationTabbedPane.addTab("Appointment queue", AppointmentQueue);

        NoShowPNL.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout NoShowPNLLayout = new javax.swing.GroupLayout(NoShowPNL);
        NoShowPNL.setLayout(NoShowPNLLayout);
        NoShowPNLLayout.setHorizontalGroup(
            NoShowPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1199, Short.MAX_VALUE)
        );
        NoShowPNLLayout.setVerticalGroup(
            NoShowPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );

        NavigationTabbedPane.addTab("No Show", NoShowPNL);

        javax.swing.GroupLayout BackgroundPNLLayout = new javax.swing.GroupLayout(BackgroundPNL);
        BackgroundPNL.setLayout(BackgroundPNLLayout);
        BackgroundPNLLayout.setHorizontalGroup(
            BackgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPNLLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(NavigationTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        BackgroundPNLLayout.setVerticalGroup(
            BackgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPNLLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(NavigationTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GPEmailField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPEmailField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPEmailField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeField;
    private javax.swing.JLabel AgeLBL;
    private javax.swing.JFormattedTextField AppointmentNumberFormattedField;
    private javax.swing.JLabel AppointmentNumberLBL;
    private javax.swing.JPanel AppointmentQueue;
    private javax.swing.JLabel AppointmentQueueLBL;
    private javax.swing.JTable AppointmentQueueTBL;
    private javax.swing.JPanel BackgroundPNL;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLBL;
    private javax.swing.JTextField FirstNameFIeld;
    private javax.swing.JLabel FirstNameLBL;
    private javax.swing.JTextField GPEmailField;
    private javax.swing.JTextField GPEmailField1;
    private javax.swing.JTextField GPEmailField2;
    private javax.swing.JLabel GPEmailLBL;
    private javax.swing.JLabel GPNotesLBL;
    private javax.swing.JLabel GPNotesLBL1;
    private javax.swing.JPanel HomePNL;
    private javax.swing.JCheckBox HospitalCheck;
    private javax.swing.JTabbedPane NavigationTabbedPane;
    private javax.swing.JPanel NoShowPNL;
    private javax.swing.JButton PopulateTableBTN;
    private javax.swing.JComboBox<String> PriorityComboBox;
    private javax.swing.JLabel PriorityLBL;
    private javax.swing.JButton SaveBTN;
    private javax.swing.JTextField SurnameField;
    private javax.swing.JLabel SurnameLBL;
    private javax.swing.JComboBox<String> TestTypeComboBox;
    private javax.swing.JLabel TestTypeLBL;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JButton UpdateBTN1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
